# This is a basic workflow to help you get started with Actions

name: Zip Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install PZStudio dependency
      run: npm install -g pzstudio

    - name: Set PZStudio output folder
      run: |
        mkdir output
        pzstudio outdir "./output/"

    - name: Build Project
      run: pzstudio build

    - name: Get Date
      run: echo "today={$(date +'%Y-%m-%d')}" >> $GITHUB_ENV
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'ZomboLewd-${{ env.today }}.zip'
        directory: './output/ZomboLewd/Contents/mods/.'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    
    - name: Publish Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        files: |
          **/*.zip
